In [400]:
import numpy as np

# Basics

In [401]:
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr)) # ---> tells about the type of object etc
print(len(arr)) # --> gives number of elements in case of 1D array
print(arr.dtype) # ---> tell about wat type of data is inside arr

[10 20 30 40 50]
<class 'numpy.ndarray'>
5
int64


In [402]:
arr = np.array([[1,2,3],[4,5,6]])
print("arr : \n",arr )
print(type(arr))
print(np.ndim(arr)) # ---> tells about the dimension of the array 

arr : 
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [403]:
arr = np.array([[1,2,3],[4,5,6]],dtype=float)
print(arr)


[[1. 2. 3.]
 [4. 5. 6.]]


In [404]:
arr = np.array([[1,2,3],[4,5,6]],dtype=str)
print(arr)
print(len(arr)) # ---> will give no of rows in case of 2d array

[['1' '2' '3']
 ['4' '5' '6']]
2


In [405]:
arr = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9],
     [0,0,0]]
)
print(arr)
print("Shape : ",np.shape(arr)) #---> gives the  number of rows and cols


[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]
Shape :  (4, 3)


## Accessing/Changing specific elements ,rows & cols etc

In [406]:
arr = np.array(
    [[1,2,3,4,5,6,7],
     [8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [407]:
# To Get a specific element ---> array[r,c]
print(arr)
print("1st row Second col element--> ",arr[1,2])
print(arr[0,5])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
1st row Second col element-->  10
6


In [408]:
# To Get a sepecific row from a numpy array
arr1 = np.array(
    [[1,2,3,4,5],
     [10,20,30,40,50]
    ]
)
print(arr1)
arr1[0,:] # ---> arr[row start : row end , col start , col end]

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


array([1, 2, 3, 4, 5])

In [409]:
arr1[:,2:4]

array([[ 3,  4],
       [30, 40]])

In [410]:
# numpy arrays are mutable 
arr1[1,2] = 300
arr1

array([[  1,   2,   3,   4,   5],
       [ 10,  20, 300,  40,  50]])

## Zeros / Ones Method in Numpy

In [411]:
zeroArr = np.zeros((3,4)) # ----> creates array with zeros
zeroArr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [412]:
zeroArr1 = np.zeros((3,3),dtype="int")
zeroArr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [413]:
onesaArr = np.ones((3,3)) # ----> creates array with ones
onesaArr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [414]:
onesaArr1 = np.ones((3,3),dtype=int)
onesaArr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [415]:
fullArr = np.full((3,3),7)  # ---> fills the array with the element that we pass
fullArr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [416]:
randArr = np.random.rand(4,4) # --> creates a matrix with random values
randArr

array([[0.60115167, 0.7936778 , 0.58631685, 0.68762264],
       [0.03532723, 0.69885585, 0.66482656, 0.65883798],
       [0.16138033, 0.41350708, 0.1697052 , 0.37129062],
       [0.31493306, 0.43184907, 0.24922751, 0.38295217]])

In [417]:
randArr1 = np.random.randint(-5,5,size=(3,3)) # --> creates a matrix with random integers within the range
randArr1

array([[ 3,  1, -5],
       [-1,  4,  1],
       [ 0, -3, -2]], dtype=int32)

In [418]:
idenArr = np.identity(5,dtype="int") # ---> creates an identity matrix wirh specified row
idenArr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Practice Questions

### Question 1 
Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [419]:

a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

print(a[:3,-5:])

[[ 2  3  4  5  6]
 [20 30 40 50 60]
 [12 12 12 12 12]]


### Question - 2
Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

In [420]:
n  = 5
# Create an (nxn) array with all zeros
a = np.zeros((n,n),dtype=int)
print(a)
print("-------------")
# Make the middle row and column all 1s
a[n//2,:]=1
a[:,n//2]=1
print(a)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
-------------
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


## Arithmetic Operations with NumPy - Maths + Stats

In [421]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [422]:
a1 = a1+100
a1

array([101, 102, 103, 104])

In [423]:
print(np.max(a1))
print(np.min(a1))
print(np.mean(a1))

104
101
102.5


In [424]:
a1 = np.array([[1,2,3,4], [5,6,7,8]])
print("max : " ,np.max(a1))
print("min : " ,np.min(a1))
print("Sum : " ,np.sum(a1))


print()

max :  8
min :  1
Sum :  36



In [425]:

np.min(a1, axis=0)

array([1, 2, 3, 4])

In [426]:

np.min(a1, axis=1)

array([1, 5])

In [427]:

np.sum(a1, axis=1)

array([10, 26])